# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: RedtRocks.Glance
PackageVersion: 0.4.2
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
FileExtensions:
- pdf
- ai
- ps
- eps
- epsf
- xps
- oxps
- cbz
- jpg
- jpeg
- jfif
- png
- apng
- gif
- webp
- bmp
- dib
- ico
- svg
- avif
- tif
- tiff
- heic
- heif
- hif
- jp2
- j2k
- jpf
- jpx
- jxl
- jxr
- wdp
- hdp
- exr
- hdr
- tga
- dds
- qoi
- ppm
- pgm
- pbm
- pam
- pnm
- icns
- psd
- cr2
- cr3
- crw
- nef
- nrw
- arw
- srf
- sr2
- raf
- orf
- rw2
- raw
- dng
- pef
- srw
- x3f
- erf
- mef
- mos
- mrw
- kdc
- dcr
- 3fr
- fff
- iiq
- rwl
- gpr
- glb
- gltf
- obj
- stl
- ply
- fbx
- usdz
- usda
- usdc
- dae
- 3mf
- 3ds
ProductCode: Glance
AppsAndFeaturesEntries:
- DisplayName: Glance
  Publisher: Glance contributors
  ProductCode: Glance
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RedtRocks/glance/releases/download/v0.4.2/Glance-v0.4.2-windows-x64-setup.exe
  InstallerSha256: 9A7B088B295FC578F21DD65FC7A550131B046C91705C2FAF50B0E45EC69AE358
- Architecture: arm64
  InstallerUrl: https://github.com/RedtRocks/glance/releases/download/v0.4.2/Glance-v0.4.2-windows-arm64-setup.exe
  InstallerSha256: 3113B3D70C063B9A082A51BB6D264195E29F852DAEF116EF13EF2A21466F480F
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-09-27
