# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: RedtRocks.Glance
PackageVersion: 0.6.4
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
FileExtensions:
- pdf
- ai
- ps
- eps
- epsf
- xps
- oxps
- cbz
- jpg
- jpeg
- jfif
- png
- apng
- gif
- webp
- bmp
- dib
- ico
- svg
- avif
- tif
- tiff
- heic
- heif
- hif
- jp2
- j2k
- jpf
- jpx
- jxl
- jxr
- wdp
- hdp
- exr
- hdr
- tga
- dds
- qoi
- ppm
- pgm
- pbm
- pam
- pnm
- icns
- psd
- cr2
- cr3
- crw
- nef
- nrw
- arw
- srf
- sr2
- raf
- orf
- rw2
- raw
- dng
- pef
- srw
- x3f
- erf
- mef
- mos
- mrw
- kdc
- dcr
- 3fr
- fff
- iiq
- rwl
- gpr
- glb
- gltf
- obj
- stl
- ply
- fbx
- usdz
- usda
- usdc
- dae
- 3mf
- 3ds
ProductCode: Glance
AppsAndFeaturesEntries:
- DisplayName: Glance
  Publisher: Glance contributors
  ProductCode: Glance
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RedtRocks/glance/releases/download/v0.6.4/Glance-v0.6.4-windows-x64-setup.exe
  InstallerSha256: 3B24A4BD6109B964DA649284B5416BC6DAF092908990511241FE4C4211426AA5
- Architecture: arm64
  InstallerUrl: https://github.com/RedtRocks/glance/releases/download/v0.6.4/Glance-v0.6.4-windows-arm64-setup.exe
  InstallerSha256: 88DD2A409A6682FDC4E3551FB2289F39C71C77B3D4349B386F1C6A063CF7E126
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-10-07
